# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_from_tiledb_sparse <- function(file, attribute, cache_size, concurrency_level) {
    .Call('_beachmat_tiledb_initialize_from_tiledb_sparse', PACKAGE = 'beachmat.tiledb', file, attribute, cache_size, concurrency_level)
}

initialize_from_tiledb_dense <- function(file, attribute, cache_size, concurrency_level) {
    .Call('_beachmat_tiledb_initialize_from_tiledb_dense', PACKAGE = 'beachmat.tiledb', file, attribute, cache_size, concurrency_level)
}

load_dense <- function(uri, attribute, cache_size, num_threads, concurrency_level) {
    .Call('_beachmat_tiledb_load_dense', PACKAGE = 'beachmat.tiledb', uri, attribute, cache_size, num_threads, concurrency_level)
}

load_sparse <- function(uri, attribute, cache_size, num_threads, concurrency_level) {
    .Call('_beachmat_tiledb_load_sparse', PACKAGE = 'beachmat.tiledb', uri, attribute, cache_size, num_threads, concurrency_level)
}

